checks:
    php:
        code_rating: true
        duplication: false
        encourage_single_quotes: true
        encourage_shallow_comparison: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        uppercase_constants: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        newline_at_end_of_file: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        no_goto: true
        avoid_unnecessary_concatenation: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            before_parentheses:
                closure_definition: true
        braces:
            classes_functions:
                class: new-line
                closure: end-of-line
            if:
                opening: end-of-line
                else_on_new_line: true
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

tools:
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR2
    sensiolabs_security_checker: true
